"""
Train XGBoost entity-resolution matcher.

Input:
    processed/dev_candidates_5000_translit.parquet

Output:
    processed/dev_pair_features_5000_translit.parquet
    processed/xgb_matcher_v2.json

The model scores S1 -> S2/S3 candidate pairs.

Important:
The end-to-end validation metric includes ground-truth matches that
were NOT generated by the candidate generator. Therefore candidate
recall remains an explicit ceiling on final matching performance.
"""

from pathlib import Path
import argparse
import time
import difflib

import duckdb
import numpy as np
import pandas as pd
import xgboost as xgb


# ============================================================
# PATHS
# ============================================================

WORKSPACE_ROOT = Path(__file__).resolve().parents[4]
REPO_ROOT = Path(__file__).resolve().parents[3]

PROCESSED_DIR = REPO_ROOT / "processed"
TRAIN_DIR = REPO_ROOT / "student_resource" / "dataset" / "train"
if not (TRAIN_DIR / "train_ground_truth.tsv").is_file():
    TRAIN_DIR = WORKSPACE_ROOT / "student_resource" / "dataset" / "train"

S1_PATH = PROCESSED_DIR / "train_source1.parquet"
S2_PATH = PROCESSED_DIR / "train_source2.parquet"
S3_PATH = PROCESSED_DIR / "train_source3.parquet"

GT_PATH = TRAIN_DIR / "train_ground_truth.tsv"

DEFAULT_CANDIDATE_PATH = (
    PROCESSED_DIR /
    "dev_candidates_5000_translit.parquet"
)

FEATURE_PATH = (
    PROCESSED_DIR /
    "dev_pair_features_5000_translit.parquet"
)

MODEL_PATH = (
    PROCESSED_DIR /
    "xgb_matcher_v2.json"
)


# ============================================================
# ARGUMENTS
# ============================================================

def parse_args():

    parser = argparse.ArgumentParser(
        description="Train XGBoost entity matcher"
    )

    parser.add_argument(
        "--candidates",
        type=str,
        default=str(DEFAULT_CANDIDATE_PATH)
    )

    parser.add_argument(
        "--features-out",
        type=str,
        default=str(FEATURE_PATH)
    )

    parser.add_argument(
        "--model-out",
        type=str,
        default=str(MODEL_PATH)
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42
    )

    parser.add_argument(
        "--validation-fraction",
        type=float,
        default=0.20
    )

    return parser.parse_args()


# ============================================================
# NORMALIZATION HELPERS
# ============================================================

def safe_string(value):

    if pd.isna(value):
        return ""

    return str(value)


def token_set(text):

    text = safe_string(text)

    if not text:
        return set()

    return set(
        token
        for token in text.split()
        if token
    )


def jaccard(a, b):

    a = token_set(a)
    b = token_set(b)

    if not a and not b:
        return 1.0

    if not a or not b:
        return 0.0

    union = a | b

    if not union:
        return 0.0

    return len(a & b) / len(union)


def token_overlap(a, b):

    a = token_set(a)
    b = token_set(b)

    if not a or not b:
        return 0.0

    smaller = min(len(a), len(b))

    if smaller == 0:
        return 0.0

    return len(a & b) / smaller


def sequence_similarity(a, b):

    a = safe_string(a)
    b = safe_string(b)

    if not a and not b:
        return 1.0

    if not a or not b:
        return 0.0

    return difflib.SequenceMatcher(
        None,
        a,
        b
    ).ratio()


def length_ratio(a, b):

    a = safe_string(a)
    b = safe_string(b)

    la = len(a)
    lb = len(b)

    if la == 0 and lb == 0:
        return 1.0

    if la == 0 or lb == 0:
        return 0.0

    return min(la, lb) / max(la, lb)


def numeric_token_set(text):

    text = safe_string(text)

    if not text:
        return set()

    return set(
        token
        for token in text.split()
        if token.isdigit()
    )


def numeric_overlap(a, b):

    a = numeric_token_set(a)
    b = numeric_token_set(b)

    if not a or not b:
        return 0.0

    return len(a & b) / min(
        len(a),
        len(b)
    )


def has_numeric_overlap(a, b):

    return float(
        len(
            numeric_token_set(a)
            &
            numeric_token_set(b)
        ) > 0
    )


# ============================================================
# LOAD SOURCES
# ============================================================

def load_source_data():

    print("\nLoading source data...")

    s1 = pd.read_parquet(S1_PATH)

    s2 = pd.read_parquet(S2_PATH)

    s3 = pd.read_parquet(S3_PATH)

    candidate_source = pd.concat(
        [
            s2,
            s3
        ],
        ignore_index=True
    )

    # Avoid column-name collisions after merging.

    source_columns = [
        "entity_id",
        "business_name",
        "business_address",
        "country",
        "name_norm",
        "name_core",
        "name_translit",
        "address_norm",
        "postal_code",
        "numeric_tokens",
        "country_norm",
    ]

    source_columns = [
        c
        for c in source_columns
        if c in s1.columns
        and c in candidate_source.columns
    ]

    s1 = s1[
        source_columns
    ].copy()

    candidate_source = candidate_source[
        source_columns
    ].copy()

    print(
        f"S1 rows : {len(s1):,}"
    )

    print(
        f"S2+S3 rows : {len(candidate_source):,}"
    )

    return s1, candidate_source


# ============================================================
# FEATURE EXTRACTION
# ============================================================

def build_pair_features(
    candidates,
    s1,
    candidate_source
):

    print("\nBuilding pair features...")

    s1_indexed = s1.set_index(
        "entity_id",
        drop=False
    )

    candidate_indexed = candidate_source.set_index(
        "entity_id",
        drop=False
    )

    records = []

    feature_names = [
        "name_exact",
        "name_core_exact",
        "name_translit_exact",

        "name_similarity",
        "name_jaccard",
        "name_token_overlap",
        "name_length_ratio",

        "address_exact",
        "address_similarity",
        "address_jaccard",
        "address_token_overlap",
        "address_length_ratio",

        "country_match",
        "postal_match",

        "numeric_overlap",
        "has_numeric_overlap",

        "candidate_is_s2",
        "candidate_is_s3",

        "name_address_similarity",
        "both_exact",
    ]

    for row in candidates.itertuples(
        index=False
    ):

        s1_id = row.source1_entity_id
        candidate_id = row.candidate_entity_id

        try:

            s = s1_indexed.loc[s1_id]

            c = candidate_indexed.loc[candidate_id]

        except KeyError:

            continue

        s_name = safe_string(
            s["name_norm"]
        )

        c_name = safe_string(
            c["name_norm"]
        )

        s_core = safe_string(
            s["name_core"]
        )

        c_core = safe_string(
            c["name_core"]
        )

        s_translit = safe_string(
            s["name_translit"]
        )

        c_translit = safe_string(
            c["name_translit"]
        )

        s_address = safe_string(
            s["address_norm"]
        )

        c_address = safe_string(
            c["address_norm"]
        )

        s_country = safe_string(
            s["country_norm"]
        )

        c_country = safe_string(
            c["country_norm"]
        )

        s_postal = safe_string(
            s["postal_code"]
        )

        c_postal = safe_string(
            c["postal_code"]
        )

        s_numeric = safe_string(
            s["numeric_tokens"]
        )

        c_numeric = safe_string(
            c["numeric_tokens"]
        )

        name_similarity = sequence_similarity(
            s_name,
            c_name
        )

        address_similarity = sequence_similarity(
            s_address,
            c_address
        )

        feature_row = {

            "source1_entity_id":
                s1_id,

            "candidate_entity_id":
                candidate_id,

            "label":
                int(row.label),

            # ----------------------------
            # NAME
            # ----------------------------

            "name_exact":
                float(
                    s_name == c_name
                    and s_name != ""
                ),

            "name_core_exact":
                float(
                    s_core == c_core
                    and s_core != ""
                ),

            "name_translit_exact":
                float(
                    s_translit == c_translit
                    and s_translit != ""
                ),

            "name_similarity":
                name_similarity,

            "name_jaccard":
                jaccard(
                    s_core,
                    c_core
                ),

            "name_token_overlap":
                token_overlap(
                    s_core,
                    c_core
                ),

            "name_length_ratio":
                length_ratio(
                    s_name,
                    c_name
                ),

            # ----------------------------
            # ADDRESS
            # ----------------------------

            "address_exact":
                float(
                    s_address == c_address
                    and s_address != ""
                ),

            "address_similarity":
                address_similarity,

            "address_jaccard":
                jaccard(
                    s_address,
                    c_address
                ),

            "address_token_overlap":
                token_overlap(
                    s_address,
                    c_address
                ),

            "address_length_ratio":
                length_ratio(
                    s_address,
                    c_address
                ),

            # ----------------------------
            # COUNTRY / POSTAL
            # ----------------------------

            "country_match":
                float(
                    s_country == c_country
                    and s_country != ""
                ),

            "postal_match":
                float(
                    s_postal == c_postal
                    and s_postal != ""
                ),

            # ----------------------------
            # NUMERIC
            # ----------------------------

            "numeric_overlap":
                numeric_overlap(
                    s_numeric,
                    c_numeric
                ),

            "has_numeric_overlap":
                has_numeric_overlap(
                    s_numeric,
                    c_numeric
                ),

            # ----------------------------
            # SOURCE
            # ----------------------------

            "candidate_is_s2":
                float(
                    str(candidate_id).startswith("S2")
                ),

            "candidate_is_s3":
                float(
                    str(candidate_id).startswith("S3")
                ),

            # ----------------------------
            # CROSS-FIELD
            # ----------------------------

            "name_address_similarity":
                (
                    name_similarity *
                    address_similarity
                ),

            "both_exact":
                float(
                    s_name == c_name
                    and s_address == c_address
                    and s_name != ""
                    and s_address != ""
                ),
        }

        records.append(
            feature_row
        )

    feature_df = pd.DataFrame(
        records
    )

    print(
        f"Feature rows : {len(feature_df):,}"
    )

    print(
        f"Positive labels : "
        f"{feature_df['label'].sum():,}"
    )

    print(
        f"Feature count : "
        f"{len(feature_names)}"
    )

    return feature_df, feature_names


# ============================================================
# GROUND TRUTH FOR END-TO-END VALIDATION
# ============================================================

def load_ground_truth_sets(
    validation_s1_ids
):

    print(
        "\nLoading full ground truth for "
        "end-to-end validation..."
    )

    gt = pd.read_csv(
        GT_PATH,
        sep="\t"
    )

    validation_ids = set(
        str(x)
        for x in validation_s1_ids
    )

    gt_sets = {}

    for row in gt.itertuples(
        index=False
    ):

        s1_id = str(
            row.source1_entity_id
        )

        if s1_id not in validation_ids:
            continue

        raw = getattr(
            row,
            "matched_entity_ids"
        )

        if pd.isna(raw):
            gt_sets[s1_id] = set()
            continue

        raw = str(raw).strip()

        if not raw:
            gt_sets[s1_id] = set()
            continue

        # Handle:
        # ['S2-1', 'S3-2']
        # ["S2-1", "S3-2"]
        # S2-1,S3-2

        raw = (
            raw
            .replace("[", "")
            .replace("]", "")
            .replace("'", "")
            .replace('"', "")
        )

        ids = set(
            x.strip()
            for x in raw.split(",")
            if x.strip()
        )

        gt_sets[s1_id] = ids

    # Important:
    # S1 records that do not occur in gt_sets get an empty
    # ground-truth set only if the source row exists.
    for s1_id in validation_ids:

        if s1_id not in gt_sets:
            gt_sets[s1_id] = set()

    print(
        f"Validation S1 ground-truth sets : "
        f"{len(gt_sets):,}"
    )

    return gt_sets


# ============================================================
# F0.5
# ============================================================

def f05_from_sets(
    predicted,
    truth
):

    predicted = set(predicted)
    truth = set(truth)

    if not predicted and not truth:
        return 1.0

    if not predicted and truth:
        return 0.0

    if predicted and not truth:
        return 0.0

    tp = len(
        predicted & truth
    )

    precision = (
        tp / len(predicted)
        if predicted
        else 0.0
    )

    recall = (
        tp / len(truth)
        if truth
        else 0.0
    )

    if precision == 0.0 and recall == 0.0:
        return 0.0

    beta_squared = 0.5 ** 2

    return (
        (1 + beta_squared)
        * precision
        * recall
        /
        (
            beta_squared * precision
            +
            recall
        )
    )


# ============================================================
# SPLIT BY S1
# ============================================================

def split_by_s1(
    feature_df,
    validation_fraction,
    seed
):

    rng = np.random.default_rng(
        seed
    )

    all_s1 = np.array(
        feature_df[
            "source1_entity_id"
        ].unique()
    )

    rng.shuffle(
        all_s1
    )

    n_validation = int(
        len(all_s1)
        * validation_fraction
    )

    validation_ids = set(
        all_s1[
            :n_validation
        ]
    )

    train_mask = (
        ~feature_df[
            "source1_entity_id"
        ].isin(validation_ids)
    )

    valid_mask = (
        feature_df[
            "source1_entity_id"
        ].isin(validation_ids)
    )

    train_df = feature_df[
        train_mask
    ].copy()

    valid_df = feature_df[
        valid_mask
    ].copy()

    print("\nSplit by S1 entity")

    print(
        f"Train pairs : {len(train_df):,}"
    )

    print(
        f"Validation pairs : {len(valid_df):,}"
    )

    print(
        f"Train S1 : "
        f"{train_df['source1_entity_id'].nunique():,}"
    )

    print(
        f"Validation S1 : "
        f"{len(validation_ids):,}"
    )

    print(
        f"Train positives : "
        f"{train_df['label'].sum():,}"
    )

    print(
        f"Validation positives : "
        f"{valid_df['label'].sum():,}"
    )

    return (
        train_df,
        valid_df,
        validation_ids
    )


# ============================================================
# MODEL TRAINING
# ============================================================

def train_model(
    train_df,
    feature_names,
    seed
):

    X_train = train_df[
        feature_names
    ]

    y_train = train_df[
        "label"
    ]

    positives = int(
        y_train.sum()
    )

    negatives = (
        len(y_train)
        - positives
    )

    scale_pos_weight = (
        negatives / positives
        if positives > 0
        else 1.0
    )

    print("\nXGBoost training")

    print(
        f"Positive : {positives:,}"
    )

    print(
        f"Negative : {negatives:,}"
    )

    print(
        f"scale_pos_weight : "
        f"{scale_pos_weight:.2f}"
    )

    model = xgb.XGBClassifier(

        n_estimators=700,

        max_depth=7,

        learning_rate=0.05,

        subsample=0.85,

        colsample_bytree=0.85,

        min_child_weight=3,

        objective="binary:logistic",

        eval_metric="logloss",

        tree_method="hist",

        scale_pos_weight=scale_pos_weight,

        n_jobs=-1,

        random_state=seed,

    )

    model.fit(
        X_train,
        y_train
    )

    return model


# ============================================================
# CONDITIONAL F0.5
# ============================================================

def conditional_macro_f05(
    valid_df,
    probabilities,
    threshold
):

    temp = valid_df[
        [
            "source1_entity_id",
            "candidate_entity_id",
            "label"
        ]
    ].copy()

    temp[
        "probability"
    ] = probabilities

    temp[
        "prediction"
    ] = (
        temp["probability"]
        >= threshold
    ).astype(int)

    scores = []

    for s1_id, group in temp.groupby(
        "source1_entity_id"
    ):

        predicted = set(
            group.loc[
                group["prediction"] == 1,
                "candidate_entity_id"
            ]
        )

        truth = set(
            group.loc[
                group["label"] == 1,
                "candidate_entity_id"
            ]
        )

        scores.append(
            f05_from_sets(
                predicted,
                truth
            )
        )

    if not scores:
        return 0.0

    return float(
        np.mean(scores)
    )


# ============================================================
# TRUE END-TO-END F0.5
# ============================================================

def end_to_end_macro_f05(
    valid_df,
    probabilities,
    threshold,
    all_validation_s1_ids,
    gt_sets
):

    temp = valid_df[
        [
            "source1_entity_id",
            "candidate_entity_id"
        ]
    ].copy()

    temp[
        "probability"
    ] = probabilities

    temp[
        "prediction"
    ] = (
        temp["probability"]
        >= threshold
    ).astype(int)

    predictions = {}

    for s1_id, group in temp.groupby(
        "source1_entity_id"
    ):

        predictions[
            str(s1_id)
        ] = set(
            str(x)
            for x in group.loc[
                group["prediction"] == 1,
                "candidate_entity_id"
            ]
        )

    scores = []

    for s1_id in all_validation_s1_ids:

        s1_id = str(s1_id)

        predicted = predictions.get(
            s1_id,
            set()
        )

        truth = gt_sets.get(
            s1_id,
            set()
        )

        scores.append(
            f05_from_sets(
                predicted,
                truth
            )
        )

    if not scores:
        return 0.0

    return float(
        np.mean(scores)
    )


# ============================================================
# THRESHOLD SWEEP
# ============================================================

def threshold_sweep(
    valid_df,
    probabilities,
    validation_s1_ids,
    gt_sets
):

    print("\n" + "=" * 90)
    print("THRESHOLD SWEEP")
    print("=" * 90)

    thresholds = [
        0.50,
        0.60,
        0.70,
        0.75,
        0.80,
        0.85,
        0.90,
        0.92,
        0.94,
        0.95,
        0.96,
        0.97,
        0.98,
        0.99,
    ]

    results = []

    print(
        f"{'Threshold':>10}"
        f"{'Conditional F0.5':>20}"
        f"{'End-to-End F0.5':>20}"
        f"{'Predicted':>12}"
    )

    print(
        "-" * 70
    )

    for threshold in thresholds:

        conditional = conditional_macro_f05(
            valid_df,
            probabilities,
            threshold
        )

        end_to_end = end_to_end_macro_f05(
            valid_df,
            probabilities,
            threshold,
            validation_s1_ids,
            gt_sets
        )

        predicted = int(
            (
                probabilities
                >= threshold
            ).sum()
        )

        print(
            f"{threshold:>10.2f}"
            f"{conditional:>20.4f}"
            f"{end_to_end:>20.4f}"
            f"{predicted:>12,}"
        )

        results.append(
            {
                "threshold": threshold,
                "conditional_f05": conditional,
                "end_to_end_f05": end_to_end,
                "predicted": predicted,
            }
        )

    return results


# ============================================================
# FEATURE IMPORTANCE
# ============================================================

def print_feature_importance(
    model,
    feature_names
):

    print("\n" + "=" * 70)
    print("FEATURE IMPORTANCE")
    print("=" * 70)

    importance = pd.Series(
        model.feature_importances_,
        index=feature_names
    ).sort_values(
        ascending=False
    )

    for name, value in importance.items():

        print(
            f"{name:30s}"
            f"{value:.6f}"
        )


# ============================================================
# MAIN
# ============================================================

def main():

    start = time.time()

    args = parse_args()

    candidate_path = Path(
        args.candidates
    )

    feature_path = Path(
        args.features_out
    )

    model_path = Path(
        args.model_out
    )

    # --------------------------------------------------------
    # Load candidates
    # --------------------------------------------------------

    print("\nLoading candidate pairs...")

    candidates = pd.read_parquet(
        candidate_path
    )

    print(
        f"Candidate pairs : "
        f"{len(candidates):,}"
    )

    print(
        f"Candidate positives : "
        f"{candidates['label'].sum():,}"
    )

    # --------------------------------------------------------
    # Load sources
    # --------------------------------------------------------

    s1, candidate_source = (
        load_source_data()
    )

    # --------------------------------------------------------
    # Build features
    # --------------------------------------------------------

    feature_df, feature_names = (
        build_pair_features(
            candidates,
            s1,
            candidate_source
        )
    )

    feature_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    feature_df.to_parquet(
        feature_path,
        index=False
    )

    print(
        f"\nSaved features -> "
        f"{feature_path}"
    )

    # --------------------------------------------------------
    # Split
    # --------------------------------------------------------

    (
        train_df,
        valid_df,
        validation_ids
    ) = split_by_s1(
        feature_df,
        args.validation_fraction,
        args.seed
    )

    # --------------------------------------------------------
    # Ground truth for END-TO-END validation
    # --------------------------------------------------------

    gt_sets = load_ground_truth_sets(
        validation_ids
    )

    # --------------------------------------------------------
    # Train
    # --------------------------------------------------------

    model = train_model(
        train_df,
        feature_names,
        args.seed
    )

    # --------------------------------------------------------
    # Predict
    # --------------------------------------------------------

    probabilities = model.predict_proba(
        valid_df[
            feature_names
        ]
    )[:, 1]

    # --------------------------------------------------------
    # Thresholds
    # --------------------------------------------------------

    results = threshold_sweep(
        valid_df,
        probabilities,
        validation_ids,
        gt_sets
    )

    # Best threshold according to true end-to-end validation.

    best = max(
        results,
        key=lambda x: x["end_to_end_f05"]
    )

    print("\n" + "=" * 90)
    print("BEST END-TO-END VALIDATION RESULT")
    print("=" * 90)

    print(
        f"Threshold          : "
        f"{best['threshold']:.2f}"
    )

    print(
        f"Conditional F0.5    : "
        f"{best['conditional_f05']:.4f}"
    )

    print(
        f"End-to-End F0.5     : "
        f"{best['end_to_end_f05']:.4f}"
    )

    print(
        f"Predicted matches   : "
        f"{best['predicted']:,}"
    )

    # --------------------------------------------------------
    # Feature importance
    # --------------------------------------------------------

    print_feature_importance(
        model,
        feature_names
    )

    # --------------------------------------------------------
    # Save model
    # --------------------------------------------------------

    model_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    model.save_model(
        model_path
    )

    print(
        f"\nSaved model -> "
        f"{model_path}"
    )

    elapsed = time.time() - start

    print(
        f"\nTotal runtime : "
        f"{elapsed:.1f} seconds"
    )


if __name__ == "__main__":
    main()